name: PR test

on:
  pull_request:
    branches:
      - main
  workflow_dispatch: {}


jobs:
  build:
    name: pr-test
    runs-on: dev-workstations

    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          # Allow goreleaser to access older tag information.
          fetch-depth: 0

      - uses: actions/setup-go@41dfa10bad2bb2ae585af6ee5bb4d7d973ad74ed # v5.1.0
        with:
          go-version-file: 'go.mod'
          # cache: true

      - name: Build
        run: make

      - name: Setup test env
        run: |
          cat <<EOF> test-env.yaml
            ${{ secrets.PROVIDER_ACC_TEST_ENV }}
          EOF

      - name: Acceptance Test
        run: make testacc
