name: PR test

on:
  pull_request:
    branches:
      - main
  workflow_dispatch: {}


jobs:
  build:
    name: pr-test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          # Allow goreleaser to access older tag information.
          fetch-depth: 0

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.7.5"

      - uses: actions/setup-go@0aaccfd150d50ccaeb58ebd88d36e91967a5f35b # v5.4.0
        with:
          go-version-file: 'go.mod'
          # cache: true

      - name: Build
        run: make

      - name: Setup test env
        run: |
          cat <<EOF> test-env.yaml
            ${{ secrets.PROVIDER_ACC_TEST_ENV }}
          EOF

      - name: Acceptance Test
        run: make testacc
