name: PR test

on:
  pull_request:
    branches:
      - main
  workflow_dispatch: {}


jobs:
  build:
    name: pr-test
    runs-on: dev-workstations

    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          # Allow goreleaser to access older tag information.
          fetch-depth: 0

      - uses: actions/setup-go@0a12ed9d6a96ab950c8f026ed9f722fe0da7ef32 # v5.0.2
        with:
          go-version-file: 'go.mod'
          cache: true

      - name: Build
        run: make

      - name: Setup test env
        run: |
          cat <<EOF> test-env.yaml
            ${{ secrets.PROVIDER_ACC_TEST_ENV }}
          EOF

      - name: Acceptance Test
        run: make testacc
